version: "3.8"
services:
  api:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    networks:
      - mern-network
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - api
    stdin_open: true
    tty: true
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge
