version: "3.8"
services:
  api:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    tty: true